name: Push events to mail
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.10'
      - run: python main.py